export interface Violation {
  name: string;
  jailTime: string;
  fine?: string;
  explanation?: string;
}

export interface PenalCodeCategory {
  id: string;
  name: string;
  subtitle: string;
  icon: string;
  color: string;
  columns: ('name' | 'jailTime' | 'fine' | 'explanation')[];
  violations: Violation[];
}

export const penalCodeCategories: PenalCodeCategory[] = [
  {
    id: 'traffic-violations',
    name: 'Traffic Violations',
    subtitle: 'May result in suspended or revoked license, a fine and possible jail time',
    icon: 'fa-car',
    color: '#3b82f6',
    columns: ['name', 'jailTime', 'fine', 'explanation'],
    violations: [
      { name: 'Reckless Driving', jailTime: '30 seconds', fine: '$1000', explanation: 'Careless and unlawful operation of a vehicle.' },
      { name: 'Driving without a license', jailTime: '20 seconds', fine: '$750', explanation: 'Operating a motor vehicle without proper paperwork.' },
      { name: 'Driving without headlights or tail lights', jailTime: 'N/A', fine: '$150', explanation: 'Operation of a vehicle without use of headlights or tail lights in an appropriate situation.' },
      { name: 'Excessive vehicle noise', jailTime: 'N/A', fine: '$200', explanation: 'Unnecessary or too much sound.' },
      { name: 'Failure to obey a traffic control device', jailTime: 'N/A', fine: '$250', explanation: 'Violation of intersection lights, stop and give way signs.' },
      { name: 'Failure to maintain lanes', jailTime: 'N/A', fine: '$500', explanation: 'Being in multiple lanes at once or swerving in between lanes.' },
      { name: 'Failure to yield to a pedestrian', jailTime: 'N/A', fine: '$250', explanation: 'Failing to yield to a pedestrian in a marked crosswalk.' },
      { name: 'Failure to yield to an emergency vehicle', jailTime: 'N/A', fine: '$500', explanation: 'Failing to yield to an Emergency vehicle with red and or blue lights.' },
      { name: 'Illegal U-Turn', jailTime: 'N/A', fine: '$200', explanation: 'U-Turn conducted in either a disallowed zone or an unsafe turn.' },
      { name: 'Illegal parking', jailTime: 'N/A', fine: '$250', explanation: 'Parking illegally in a zone disallowing parking.' },
      { name: 'Impeding flow of traffic', jailTime: 'N/A', fine: '$400', explanation: 'Interrupting the flow of traffic in anyway for an extended period of time.' },
      { name: 'Driving without insurance', jailTime: 'N/A', fine: '$450', explanation: 'Self explanatory' },
      { name: 'Speeding 10-19', jailTime: 'N/A', fine: '$150', explanation: 'Failing to obey posted speed signs.' },
      { name: 'Speeding 20-29', jailTime: 'N/A', fine: '$250', explanation: 'Failing to obey posted speed signs.' },
      { name: 'Speeding 30 or over', jailTime: '30 seconds', fine: '$500', explanation: 'Failing to obey posted speed signs.' },
      { name: 'Unlawful vehicle modification', jailTime: 'N/A', fine: '$500', explanation: 'Red and blue underglow, pure black window tint or police horn.' },
      { name: 'Unroadworthy vehicle', jailTime: 'N/A', fine: '$350', explanation: 'Operation of a motorized vehicle that is not fit to be operated on a public roads. No license plates, expired tabs, cracked windshield.' },
      { name: 'Possession of burglary Tools', jailTime: '35 seconds', fine: '$800', explanation: 'A person who has in their possession tools necessary to commit burglary such as a crowbar with a screwdriver, shimmy, or other appropriate items.' },
      { name: 'Improper use of a motor vehicle', jailTime: 'N/A', fine: '$400', explanation: 'Improper use of a motor vehicle like not wearing a helmet on a motorcycle, or seatbelt in car.' },
    ],
  },
  {
    id: 'petty-misdemeanors',
    name: 'Petty Misdemeanors',
    subtitle: "A small violation, prohibited by a statute. But it's not a crime. Usually results in a fine",
    icon: 'fa-scale-balanced',
    color: '#f59e0b',
    columns: ['name', 'jailTime', 'fine', 'explanation'],
    violations: [
      { name: 'Disorderly conduct', jailTime: '15 seconds', fine: '$250', explanation: 'Unruly behaviour constituting a minor offense.' },
      { name: 'Disturbing the peace', jailTime: '20 seconds', fine: '$300', explanation: "When a person's words or conduct jeopardizes another's rights to peace and tranquility." },
      { name: 'Loitering', jailTime: 'N/A', fine: '$250', explanation: 'To delay or linger in the vicinity of a posted property with no purpose or lawful reason.' },
      { name: 'Public intoxication', jailTime: '25 seconds', fine: '$800', explanation: 'A person who is found in any public place under the influence of alcohol.' },
      { name: 'Jaywalking', jailTime: 'N/A', fine: '$100', explanation: 'Crossing a public road at an otherwise unmarked crossing.' },
    ],
  },
  {
    id: 'misdemeanors',
    name: 'Misdemeanors',
    subtitle: 'Results in a fine, jail sentence or both depending on the crime',
    icon: 'fa-gavel',
    color: '#f97316',
    columns: ['name', 'jailTime', 'fine', 'explanation'],
    violations: [
      { name: 'Assault', jailTime: '1 Minute', fine: '$3500', explanation: 'A person who intentionally put another in the reasonable belief of physical harm or offensive contact.' },
      { name: 'Aggravated Assault', jailTime: '1 minute 20 seconds', fine: '$6000', explanation: 'A person who continuously intentionally put another in the reasonable belief of severe physical harm or offensive contact.' },
      { name: 'Aiding and abetting', jailTime: '45 seconds', fine: '$2000', explanation: 'The act of aiding somebody or a group in the process of a crime.' },
      { name: 'Battery', jailTime: '1 minute', fine: '$2500', explanation: 'A person who uses a unlawful force or violence to cause physical harm.' },
      { name: 'Aggravated Battery', jailTime: '1 minute 15 seconds', fine: '$3500', explanation: 'A person who uses great or continued force or violence to cause physical harm.' },
      { name: 'Breaking and entering', jailTime: '45 seconds', fine: '$1800', explanation: 'The action of forcing your way into a property you do not have permission to be in.' },
      { name: 'Brandishing a firearm', jailTime: '30 seconds', fine: '$800', explanation: 'The act of holding or pointing a unconcealed weapon on or attached to your body.' },
      { name: 'Bribery', jailTime: '45 seconds', fine: '$2000', explanation: 'Attempting to give items of value and worth to receive a favorable outcome.' },
      { name: 'Contempt of court', jailTime: '30 seconds', fine: '$2500', explanation: 'A person who willfully disobeys, disrespects, or otherwise infringes the verbal or written authority of the court.' },
      { name: 'Destruction of property', jailTime: '30 seconds', fine: '$1500', explanation: 'The act of inflicting damage to property public or private.' },
      { name: 'Drug possession Class: A, B, C', jailTime: 'A) 1 min 30 sec, B) 1 min, C) 50 sec', fine: '$2000', explanation: 'Possession of one or less pound.' },
      { name: 'DUI/DWI', jailTime: '1 minute', fine: '$3000', explanation: 'Operating a motorized vehicle while under the influence of alcohol or drugs.' },
      { name: 'Failure to follow a lawful command', jailTime: '1 minute', fine: '$1000', explanation: 'Willingly disobeying a lawful command given by a government official.' },
      { name: 'Failure to identify to a LEO', jailTime: '1 minute', fine: '$1200', explanation: 'A person who is detained or under arrest by a LEO and fails to provide their name or ID.' },
      { name: 'Failure to pay fines', jailTime: '2 minutes 30 seconds', fine: 'N/A', explanation: 'A person who fails to pay a fine or court ordered fee.' },
      { name: 'Failure to have a valid permit', jailTime: '1 minute', fine: '$1500', explanation: 'Not having a valid permit.' },
      { name: 'Filing a false complaint', jailTime: '1 minute 30 seconds', fine: '$1500', explanation: 'A person who knowingly files a false complaint, statement or document.' },
      { name: 'Indecent exposure', jailTime: '2 minutes', fine: '$1500', explanation: 'A person who intentionally exposes their naked body or genitalia.' },
      { name: 'Illegal street racing', jailTime: '1 minute 30 seconds', fine: '$4000', explanation: 'Unsanctioned and illegal form of auto racing that occurs on a public road.' },
      { name: 'Accessory to street racing', jailTime: '1 minute', fine: '$2000', explanation: 'Helping and or planning a street racing event.' },
      { name: 'Obstruction of justice', jailTime: '2 minutes 30 seconds', fine: '$1250', explanation: 'An action that shows a clear motivated attempt to stop/halt a law enforcement officer from doing their job.' },
      { name: 'Providing false information to a LEO', jailTime: '2 minutes', fine: '$800', explanation: 'Providing a government official with false information.' },
      { name: 'Public endangerment', jailTime: '1 minute', fine: '$1600', explanation: 'The act of placing the public in any kind of way.' },
      { name: 'Stalking', jailTime: '2 minutes', fine: '$3000', explanation: 'A person that follows, threatens or harasses another individual.' },
      { name: 'Sexual assault', jailTime: '3 minutes', fine: '$3000', explanation: 'A person who commits verbal abuse for the purpose of sexual arousal.' },
      { name: 'Trespassing', jailTime: '2 minutes', fine: '$500', explanation: 'Entering private property that you do not have permission to reside in.' },
      { name: 'Theft', jailTime: '2 minutes 30 seconds', fine: '$1000', explanation: "A person who takes or steals another's property." },
      { name: 'Unlawful discharge of a firearm', jailTime: '1 minute 30 seconds', fine: '$800', explanation: 'Discharge of a firearm without due cause or justifiable motive.' },
      { name: 'Vandalism', jailTime: '1 minute 30', fine: '$1500', explanation: 'A person that defaces, damages, or destroys property which belongs to another.' },
      { name: 'Withholding info from a LEO', jailTime: '2 minutes', fine: 'N/A', explanation: 'A person who intentionally withholds information from a LEO.' },
      { name: 'Failure to stop for a police vehicle', jailTime: '2 minutes', fine: '$750', explanation: 'Self explanatory' },
      { name: 'Wasting police time', jailTime: '3 minutes', fine: 'N/A', explanation: "A person who intentionally wastes a LEO's time." },
    ],
  },
  {
    id: 'felonies',
    name: 'Felonies',
    subtitle: 'A crime, typically one involving violence, regarded as more serious than a misdemeanor, and punishable by imprisonment',
    icon: 'fa-handcuffs',
    color: '#ef4444',
    columns: ['name', 'jailTime', 'explanation'],
    violations: [
      { name: 'Armed Robbery', jailTime: '3 minutes 30 seconds', explanation: 'A person who takes property from the possession of another with a weapon.' },
      { name: 'Accessory to armed robbery', jailTime: '2 minutes', explanation: 'A person who helps commit or plan to take property from the possession of another with a weapon.' },
      { name: 'Arson', jailTime: '2 minutes 30 seconds', explanation: 'A person who intentionally malicious sets fire to any structure, forest land, or property.' },
      { name: 'Assault with a deadly weapon', jailTime: '3 minutes 45 seconds', explanation: 'A person who attempts to cause or threaten immediate harm to another using a weapon to communicate that threat.' },
      { name: 'Accessory to assault with a deadly weapon', jailTime: '3 minutes', explanation: 'A person who helps commit or plan to attempt to cause or threaten immediate harm to another using a weapon to communicate that threat.' },
      { name: 'Assault on a LEO', jailTime: '4 minutes', explanation: 'A person who intentionally put another in the reasonable belief or physical harm or offensive contact to a LEO.' },
      { name: 'Attempted murder', jailTime: '4 minutes', explanation: 'A person who deliberately attempt to kill or cause life threatening.' },
      { name: 'Accessory to Attempted murder', jailTime: '3 minutes 30 seconds', explanation: 'A person who deliberately helps or plans to attempt to kill or cause life threatening harm.' },
      { name: 'Attempted murder of a LEO', jailTime: '4 minutes 45 seconds', explanation: 'A person who deliberately attempt to kill or cause life threatening harm.' },
      { name: 'Accessory to attempted murder of a LEO', jailTime: '4 minutes', explanation: 'A person who deliberately helps or cause life threatening harm of a LEO.' },
      { name: 'Corruption of a government position', jailTime: '3 minutes', explanation: 'A government employee who acts outside the interests of the public good or public justice.' },
      { name: 'Dissuading a witness or a victim', jailTime: '3 minutes', explanation: 'A person who knowingly and maliciously prevents or encourages a witness or victim from giving a testimony.' },
      { name: 'Distribution of illegal firearms', jailTime: '4 minutes', explanation: 'Selling or giving away illegal firearms.' },
      { name: 'Extortion', jailTime: '3 minutes 30 seconds', explanation: 'A person who intimidates or influences to provide or hand over properties or services.' },
      { name: 'Escape', jailTime: '4 minutes', explanation: 'A person who has been detained and arrested, booked, charged, or convicted of any crime who escapes from custody.' },
      { name: 'Accessory to escape', jailTime: '3 minutes', explanation: 'A person that helps or plans someone who has been detained and arrested, booked, charged or convicted of any crime who escapes from custody.' },
      { name: 'Felony drug possession', jailTime: 'Class A: 3 min, Class B: 2 min, Class C: 1 min', explanation: 'Possession of a illegal substance one pound or more.' },
      { name: 'Fleeing & Eluding', jailTime: '3 minutes 30 seconds', explanation: 'A person who runs away from police in a vehicle or on foot to elude arrest or questioning.' },
      { name: 'Hit & Run', jailTime: '2 minutes 30 seconds', explanation: 'Leaving the scene of an accident.' },
      { name: 'Grand Theft Auto', jailTime: '3 minutes', explanation: 'A person who has stolen a motor vehicle.' },
      { name: 'Perjury', jailTime: '2 minutes', explanation: 'A person who knowingly provides false information while under oath in a court of law.' },
      { name: 'Prostitution', jailTime: '2 minutes', explanation: 'A person who exchanges sexual acts for payment or other goods.' },
      { name: 'Pandering / Pimping', jailTime: '2 minutes 30 seconds', explanation: 'A person who solicits or advertises and supervises anyone involved in prostitution.' },
      { name: 'Possession of illegal firearm Class A', jailTime: '2 minutes 30 seconds', explanation: 'A person who was in possession of a illegal pistol or handgun.' },
      { name: 'Possession of illegal firearm Class B', jailTime: '3 minutes', explanation: 'A person who was in possession of a illegal shotgun.' },
      { name: 'Possession of illegal firearm Class C', jailTime: '4 minutes', explanation: 'A person who was in possession of a illegal fully automatic firearm.' },
      { name: 'Improper use of a motor vehicle', jailTime: '2 minutes', explanation: 'A person who excessively speeds and is driving recklessly.' },
      { name: 'Manslaughter', jailTime: '3 minutes', explanation: 'A person who unintentionally kills another.' },
      { name: 'Police Impersonation', jailTime: '3 minutes', explanation: 'A person who pretends or implies the role of a police officer.' },
      { name: 'Kidnapping', jailTime: '3 minutes 30 seconds', explanation: 'A person who detains or arrests another without their consent and unlawfully.' },
      { name: 'Murder', jailTime: '5 minutes', explanation: 'A person who unlawfully kills another.' },
      { name: 'Accessory to murder', jailTime: '4 minutes 30 seconds', explanation: 'A person who helps or plans to unlawfully kills another.' },
      { name: 'Murder of a LEO', jailTime: '6 minutes', explanation: 'A person who unlawfully kills a LEO.' },
      { name: 'Accessory to murder of a LEO', jailTime: '5 minutes', explanation: 'A person who helps or plans the unlawfully kills of a LEO.' },
      { name: 'Conspiracy to commit murder', jailTime: '3 minutes 30 seconds', explanation: 'Planning to or discussing to commit murder.' },
      { name: 'Solicitation of murder', jailTime: '4 minutes', explanation: 'Paying to have an individual(s) killed.' },
      { name: 'Sexual battery', jailTime: '3 minutes', explanation: 'A person who commits unwanted touching or sexual contact.' },
      { name: 'Resisting Arrest', jailTime: '4 minutes', explanation: 'A person who avoids apprehension from an officer by any means.' },
      { name: 'Rape', jailTime: '4 minutes 30 seconds', explanation: 'A person who forces another to engage in sexual activities.' },
      { name: 'Trespassing within a restricted facility', jailTime: '3 minutes', explanation: 'A person who, without proper authorization enters any government owned or managed facility that is secured with the intent of keeping people out.' },
      { name: 'Terrorism', jailTime: '10 minutes', explanation: 'A person who uses threats or actions against the public to cause fear at a grand scale.' },
      { name: 'Vigilantism', jailTime: '4 minutes', explanation: 'A person who attempts to effect justice according to their own understanding of right and wrong.' },
      { name: 'Possession of an illegal weapon (Knife)', jailTime: '3 minutes', explanation: 'A person who is in possession of a blade over three inches.' },
    ],
  },
  {
    id: 'other',
    name: 'Other',
    subtitle: '',
    icon: 'fa-circle-exclamation',
    color: '#8b5cf6',
    columns: ['name', 'jailTime'],
    violations: [
      { name: 'Cop/Civ baiting', jailTime: '1st offense: 5 min jail. 2nd offense: 10 min jail. 3rd offense: 15 min jail. If anybody continues to Cop/Civ bait after 3 offenses you will be contacted by an Admin.' },
      { name: 'MetaGaming', jailTime: '1st offense: 5 min jail. 2nd offense: 10 min jail. 3rd offense: 15 min jail. If anybody continues to MetaGame after 3 offenses you will be contacted by an Admin.' },
    ],
  },
];

export const columnLabels: Record<string, string> = {
  name: 'Violation',
  jailTime: 'Jail Time',
  fine: 'Fine',
  explanation: 'Explanation',
};
