import { test, expect } from '@playwright/test';
import path from 'path';

// The admin console is gated behind the admin session cookie (separate
// from the regular user session). admin.json was generated by an admin
// login; reuse it for this test so we can render the panel.
//
// We don't hit a real database — the panel's only data source is
// GET /api/v1/admin/subscription-events, which we mock with page.route.
// That keeps this test focused on the panel's rendering contract and
// independent of whether subscription_events has rows in the test DB.
test.use({ storageState: path.join(__dirname, '../../.auth/admin.json') });

test.describe('Admin → Subscriptions panel', { tag: '@admin' }, () => {
  test('renders search results from the audit endpoint', async ({ page }) => {
    await page.route('**/api/v1/admin/subscription-events*', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          data: [
            {
              _id: 'aaaaaaaaaaaaaaaaaaaaaaaa',
              provider: 'revenuecat',
              store: 'PLAY_STORE',
              eventType: 'INITIAL_PURCHASE',
              plan: 'premium_plus',
              isAnnual: false,
              productId: 'premium_plus_monthly:premium-plus-monthly',
              transactionId: 'GPA.3377-7617-2106-59661..0',
              userEmail: 'jaseysbro@example.com',
              priceUsd: 19.99,
              currency: 'USD',
              rawPayload: '{"event":{"type":"INITIAL_PURCHASE"}}',
              processingStatus: 'ok',
              createdAt: '2026-05-16T12:00:00Z',
            },
          ],
          totalCount: 1,
          page: 1,
          limit: 50,
        }),
      });
    });

    await page.goto('/admin#subscriptions');

    // The Subscriptions nav item has data-panel="subscriptions"; click it
    // to make sure the panel is active even if the hash didn't trigger.
    await page.locator('[data-panel="subscriptions"]').first().click();

    const tbody = page.locator('#subscription-events-tbody');
    await expect(tbody.locator('[data-testid="subscription-event-row"]').first()).toBeVisible();
    await expect(tbody).toContainText('GPA.3377-7617-2106-59661..0');
    await expect(tbody).toContainText('jaseysbro@example.com');
    await expect(tbody).toContainText('PLAY_STORE');
    await expect(tbody).toContainText('premium_plus');
    await expect(tbody).toContainText('$19.99');
  });

  test('searches with q param when the form is submitted', async ({ page }) => {
    let lastQ: string | null = null;
    await page.route('**/api/v1/admin/subscription-events*', async (route) => {
      const u = new URL(route.request().url());
      lastQ = u.searchParams.get('q');
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ data: [], totalCount: 0, page: 1, limit: 50 }),
      });
    });

    await page.goto('/admin#subscriptions');
    await page.locator('[data-panel="subscriptions"]').first().click();

    // First request is the initial empty-search load.
    await expect.poll(() => lastQ).toBe(null);

    await page.getByTestId('subscription-events-search').fill('GPA.3377');
    await page.getByTestId('subscription-events-submit').click();

    await expect.poll(() => lastQ).toBe('GPA.3377');
    await expect(page.locator('#subscription-events-status')).toContainText(/No events found matching "GPA.3377"/);
  });
});
